<?php require_once __DIR__ . '/../header.phtml' ?>

<h3>Agregar Modelo</h3>

<section>
    <form action="<?= BASE_URL ?>confirmar-agregar-modelo" method="POST" enctype="multipart/form-data">
        <label for="nombre">nombre</label>
        <input type="text" name="nombre" required>

        <label for="descripcion">descripcion</label>
        <input type="text" name="descripcion" required>

        <label for="categoria">categoria</label>
        <input type="text" name="categoria" required>

        <label for="imagen">Imagen:</label>
        <input type="file" name="imagen" accept="image/*">

        <button type="submit">agregar</button>
        <a href="<?=BASE_URL?>listar-modelos">cancelar</a>
    </form>
    <a href="<?= BASE_URL ?>admin">Volver</a>
</section>

<?php require_once __DIR__ . '/../footer.phtml' ?>