<?php require_once __DIR__ . '/../header.phtml' ?>

<section class="listar-calefactores">

    <h2>Lista calefactores</h2>
            <ul>
                <?php foreach ($calefactores as $c): ?>
                    <li class="lista">    
                        <?= htmlspecialchars($c->nombre) ?> 
                        <?= htmlspecialchars($c->tipo) ?>  
                        <?= htmlspecialchars($c->precio) ?>

                        <a href="<?= BASE_URL ?>calefactor/<?= $c->id_calefactor ?>"> Ver detalle </a>  
                    </li>
                <?php endforeach; ?>
            </ul>

</section>

<?php require_once __DIR__ . '/../footer.phtml' ?>