<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="<?= BASE_URL ?>assets/style.css">
    <title>db_calefactores</title>
</head>
<body>
    
    <header>
        <h1>Catalogo de Calefactores</h1>
        <nav> 
            <li><a href="<?= BASE_URL ?>calefactores">calefactores</a></li>
            <li><a href="<?= BASE_URL ?>modelos">modelos</a></li>
            <li><a href="<?= BASE_URL ?>inicio">inicio</a></li>
        </nav>

        <div class="nav">
            <?php if (isset($this->admin->id)): ?>
                <span>
                    <?= $this->admin->nombre ?>
                </span>
                <a href="<?=BASE_URL?>admin">panel administracion</a>
                <a href="<?=BASE_URL?>confirmar-logout">Cerrar sesión</a>
            <?php else: ?>
                <span>
                    <?= "User" ?>
                </span>
                <a href ="<?= BASE_URL ?>login">Iniciar sesión</a>
            <?php endif; ?>
        </div>
    </header>
<main>